### ISSUE TITLE
jwks-rsa 1.6.0 package breaking code 

### ISSUE THREAD

**Issue by firojasha** [auth0/node-jwks-rsa#103]
Hi, 
  jwks-rsa@1.6.0 is breaking our code with the below error, when we go back to jwks-rsa@1.5.0 we are not seeing the below mentioned issue and application working perfectly, 

Please check what is causing to break when install jwks-rsa@16.0 package.

src/eso/RebarESOUtils.ts:119:46 - error TS2339: Property 'publicKey' does not exist on type 'SigningKey'.
  Property 'publicKey' does not exist on type 'RsaSigningKey'.
119                         let signingKey = key.publicKey || key.rsaPublicKey;                                                ~~~~~~~~~
src/eso/RebarESOUtils.ts:119:63 - error TS2339: Property 'rsaPublicKey' does not exist on type 'SigningKey'.
  Property 'rsaPublicKey' does not exist on type 'CertSigningKey'.
119                         let signingKey = key.publicKey || key.rsaPublicKey;

Regards,
Firoj Shaik

**Comment by Doacola** [comment]
Hi @firojasha ,

Encountered the same issue today and after 30 minutes of searching managed to track it down to this commit / line:
https://github.com/auth0/node-jwks-rsa/commit/74f6fe3e66b9d9bf7de5661da772d8834c17b0ec#diff-b52768974e6bc0faccb7d4b75b162c99R58

Sadly there was no mention of this breaking change anywhere nor was there documentation update.

Working solution for now is:
```typescript
const getKey = (header, callback) => {
      client.getSigningKey(header.kid, (err, key: jwksClient.SigningKey) => {
        const signingKey =
          (key as jwksClient.CertSigningKey).publicKey ||
          (key as jwksClient.RsaSigningKey).rsaPublicKey
        callback(null, signingKey)
      })
}
```

**Comment by lemiesz** [comment]
+1 having the same error. Downgrading version for now

**Comment by firojasha** [comment]
Is there any update on this, please?

**Comment by sgil-carecloud** [comment]
experiencing the same issue

**Comment by jimmyjames** [comment]
For those encountering this issue, we sincerely apologize for the unexpected breaking change. We are evaluating the best path forward to address this; in the meantime please remain on version 1.5 if you don't need to support private certificates and/or additional agent configurations that was added in v6, or consider the suggested workarounds above.

**Comment by lbalmaceda** [comment]
Hi all. Considering the time passed since the unintended breaking change, we've released version `1.6.2` which includes a quick way to obtain the Public Key value, and resolve any TS definitions conflicts that were introduced with `1.6.0`. 

Now, instead of type-checking the value and accessing either `key.publicKey` or `key.rsaPublicKey` properties, you can directly invoke the `key.getPublicKey()` function:

```ts
const getKey = (header, callback) => {
      client.getSigningKey(header.kid, (err, key: jwksClient.SigningKey) => {
        const signingKey = key.getPublicKey()
        callback(null, signingKey)
      })
}
```

We apologize for any inconvenience that this has caused.

**Comment by Guriqbal-Singh-Alida** [comment]
@lbalmaceda please update readme with above too if its the suggested way now

**Comment by ankushknr19** [comment]
``
function getKey(header: any, callback: any) {
			client.getSigningKey(
				header.kid,
				function (_err, key: jwksClient.SigningKey | undefined) {
					const signingKey =
						(key as jwksClient.CertSigningKey).publicKey ||
						(key as jwksClient.RsaSigningKey).rsaPublicKey
					callback(null, signingKey)
				}
			)
		}
``

**Comment by ankushknr19** [comment]
`function getKey(header: any, callback: any) {
			client.getSigningKey(
				header.kid,
				function (_err, key: jwksClient.SigningKey | undefined) {
					const signingKey =
						(key as jwksClient.CertSigningKey).publicKey ||
						(key as jwksClient.RsaSigningKey).rsaPublicKey
					callback(null, signingKey)
				}
			)
		}`

**Comment by ankushknr19** [comment]
``` sh
function getKey(header: any, callback: any) {
      client.getSigningKey( header.kid, function (_err, key: jwksClient.SigningKey | undefined) {
            const signingKey =
                             (key as jwksClient.CertSigningKey).publicKey || 
                             (key as jwksClient.RsaSigningKey).rsaPublicKey
	    callback(null, signingKey)
      })
}
```
