### ISSUE TITLE
Local JWKS cache option

### ISSUE THREAD

**Issue by texonidas** [auth0/node-jwks-rsa#108]
We have a use case that is (in my opinion) not that uncommon, however I'm struggling to find a solution using this library.

We are using GraphQL on a Lambda instance, and in the current implementation that means a request to the well-known endpoint for every single request that comes through to our server, as the cache option will only persist while the instance is still alive.

Is there the potential to add a "local cache" option, such that we could set up a cron job to update our key asynchronously and have it available for our lambda instances as an env var?

**Comment by kingkong123** [comment]
Hi, my project also faces the same issue, because it is a Lambda custom authorizer, the authorizer is not able to cache the public key and making the service slow.
Does Auth0 have any plan to add the functionality on custom caches for pubic key?
