### ISSUE TITLE
How to bypass cache?

### ISSUE THREAD

**Issue by joe-ww** [auth0/node-jwks-rsa#110]
### Description

I want to use the cache feature of this library, but in the case of a signature failure, I want to try and re-fetch the keys from the JWKS endpoint.  Is there a way to tell .getSigningKey to invalidate the cache and go re-fetch?

Using v 1.6.0.

**Comment by jnardone** [comment]
@damieng not sure if you're the maintainer, but this is a problematic issue we can't work around.  Is there a way to bypass the cache, or do you have any thoughts on a code flow where we can explicitly refresh the cache in the case the cached info is stale?

**Comment by lbalmaceda** [comment]
If by bypassing the cache you mean disable it, you can do that passing `cache: false` in the options. But I couldn't find a way to force a refresh on the `JwksClient` file. If a key is not found and the cache is relatively new, it should fail as it is now with a missing key. However, if that cache is long-dated, a new one should be fetched before failing. 
I'm not the owner but there are some improvements that can be done to the cache logic.

**Comment by davidpatrick** [comment]
@joe-ww the current implementation of the cache is per KID check.  When you check a KID for the first time it will re-fetch the keys from the JWKS endpoint, it then caches the result of that check for the duration of the cache.

If you want to retry a KID or if you want to clear the cache for all KID checks ahead of the expiration, you can access the cache via `client.getSigningKey.del(KID)` or `client.getSigningKey.reset()`.  The underlying cache is powered by https://github.com/isaacs/node-lru-cache

**Comment by jnardone** [comment]
nice.  i wish there was a way that was less inside pool on the underlying tech (like client.invalidateCache(KID) or client.resetCache()) but this will work
