### ISSUE TITLE
"this" is undefined in JwksClient

### ISSUE THREAD

**Issue by Schwusch** [auth0/node-jwks-rsa#122]
### Environment

Using 1.6.2 with nodejs10.x in AWS Lambda:

`"TypeError: Cannot read property 'logger' of undefined","at getKeys (/var/task/node_modules/jwks-rsa/lib/JwksClient.js:87:12)"`

### Reproduction

This is consistently reproducable by running this code:

```typescript
import util from "util";
import jwksClient from "jwks-rsa";

const client = jwksClient({
            cache: true,
            cacheMaxEntries: 50,
            cacheMaxAge: 2 * 60 * 1000,
            jwksUri: secretUrl,
            requestHeaders: secretHeaders
        });

const getKeys = util.promisify(client.getKeys);
const keys = await getKeys()
```

**Comment by davidpatrick** [comment]
@Schwusch promisifying client.getKeys changes the local scope of the getKeys function.  You will need to rebind the client scope to the promisifyed function

```js
util.promisify(client.getKeys).bind(client);
```
