### ISSUE TITLE
Mocha test with Nock timeout issue when mocking getSigningKey request

### ISSUE THREAD

**Issue by FilipMilankoIT** [auth0/node-jwks-rsa#143]
### Description

When trying to mock getSigningKey request with Nock module the Mocha test times out. This issue started from version 1.7.0. 

Looking at Nock logs we can see that it manages to match the request but it never sends back the mock response:

`matching https://login.microsoftonline.com:443/648d66ab-8ea-49e1-97c2-a1b1a77cc39c/discovery/v2.0/keys to GET https://login.microsoftonline.com:443/648d66ab-8ea-49e1-97c2-a1b1a77cc39c/discovery/v2.0/keys: true
  nock.interceptor match {"protocol":"https:","maxRedirects":21,"maxBodyLength":10485760,"path":"/548d26ab-8caa-49e1-97c2-a1b1a06cc39c/discovery/v2.0/keys","method":"GET","headers":{"accept":"application/json, text/plain, */*","user-agent":"axios/0.19.2"},"agent":{"domain":null,"_events":....
  nock.interceptor query matching skipped +0ms
  nock.request_overrider interceptor identified, starting mocking +0ms
  nock.playback_interceptor response.rawHeaders: [ 'Content-Type', 'application/json' ] +0ms
  nock.playback_interceptor transform the response body +0ms
  nock.playback_interceptor emitting response +0ms
  nock.playback_interceptor adding body to buffer list +0ms
  nock.playback_interceptor emitting response chunk +0ms
  nock.playback_interceptor ending response stream +0ms
  Error: Timeout of 2000ms`

### Reproduction

Create a Mocha test with getSigningKey function. Use the latest Nock module for mocking the request from getSigningKey. See if the Nock returns a mock response.

### Environment
- node v12.13.0
- node-jwks-rsa v1.8.0 or v1.7.0
- nock v12.0.3
- mocha v6.2.3

**Comment by jimmyjames** [comment]
Hi @FilipMilankoIT, can you share a sample with a simple case that demonstrates the issue? Something in a gist would be perfect, thanks!
