### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by dilippatidar123** [auth0/node-jwks-rsa#150]
Hi Team,
We are getting following error.

DeprecationWarning: Buffer() is deprecated due to security and usability issues with node js latest version due to deprecated code in util.js

**/*
 * Source: http://stackoverflow.com/questions/18835132/xml-to-pem-in-node-js
 */
export function rsaPublicKeyToPEM(modulusB64, exponentB64) {
  const modulus = new Buffer(modulusB64, 'base64');
  const exponent = new Buffer(exponentB64, 'base64');**

Thanks

**Comment by cwardcode** [comment]
We're receiving this as well. Has there been any established timeline for when this may be addressed?

**Comment by jimmyjames** [comment]
Fixed with #154. We'll target publishing a new version likely next week.
