### ISSUE TITLE
Passport integration supports only RS256 algorithm

### ISSUE THREAD

**Issue by mdziardziel** [auth0/node-jwks-rsa#155]
Hi!
I have a question, because I can't find answer in docs/commits. 
I found similar question for express integration https://github.com/auth0/node-jwks-rsa/issues/107

Is there any reason why passport integration supports only `RS256` algorithm? 
https://github.com/auth0/node-jwks-rsa/blame/d842be9fc24cc3eef53ae1b41ef6a36df0bf3b33/src/integrations/passport.js#L29

`jsonwebtoken` (which is used by passport to verify jwt) supports more algorithms https://www.npmjs.com/package/jsonwebtoken#algorithms-supported

**Comment by jimmyjames** [comment]
Hi @mdziardziel, this library's purpose is to get RSA signing keys from a JWKS endpoint, which are used to verify the signature of RS256-signed tokens. That is why the support for the integrations here target RS256 only. You can read more about JWKS [here](https://auth0.com/docs/tokens/json-web-tokens/json-web-key-sets).
