### ISSUE TITLE
How to load from file ?

### ISSUE THREAD

**Issue by HuEric** [auth0/node-jwks-rsa#158]
I would like to load jwks.json from file for AWS Lambda authorizer, avoiding to make unnecessary calls to Auth0 when receiving a lot of requests.
How could I achieve this ?

Thank you

**Comment by ottokruse** [comment]
Sketchy idea --> use a HTTP mock: https://github.com/nock/nock

How would you handle key rotation though? The keys might change, which would necessitate fetching the jwks uri again

**Comment by jimmyjames** [comment]
Hi @HuEric, currently this library doesn't support fetching the keys from a file. I think this is something we should enable though, so I'll pick this one up hopefully later this week or early next week.

Do note though that the library supports caching, which minimizes excessive calls to the JWKS endpoint.
