### ISSUE TITLE
Async methods are missing in Typescript typings

### ISSUE THREAD

**Issue by ThomasPiskol** [auth0/node-jwks-rsa#164]
### Description

According to the readme this library provides async methods for the `JwksClient`:
> Note that all methods on the `JwksClient` have asynchronous equivalents, where the promisified name is suffixed with `Async`, e.g., `client.getSigningKeyAsync(kid).then(key => { /* ... */ })`;

But these methods are not included in the `index.d.ts` and therefore cannot be used in Typescript.

### Reproduction
Just take a look at the definition of `JwksClient ` in `index.d.ts`:
```typescript
declare namespace JwksRsa {
  class JwksClient {
    constructor(options: ClientOptions);

    getKeys(cb: (err: Error | null, keys: unknown) => void): void;
    getSigningKeys(cb: (err: Error | null, keys: SigningKey[]) => void): void;
    getSigningKey: (kid: string, cb: (err: Error | null, key: SigningKey) => void) => void;
  }
```
As you can see the methods  `getKeysAsync`, `getSigningKeysAsync` and `getSigningKeyAsync` are missing.
In `index.js` the async methods are defined like this:
```js
    this.getKeysAsync = promisifyIt(this.getKeys, this);
    this.getSigningKeysAsync = promisifyIt(this.getSigningKeys, this);
    this.getSigningKeyAsync = promisifyIt(this.getSigningKey, this);
```

### Environment

> Please provide the following:

- **Version of this library used:** 1.9.0
- **Version of the platform or framework used, if applicable:** n/a
- **Other relevant versions (language, server software, OS, browser):** Typescript 3.9.7
- **Other modules/plugins/libraries that might be involved:** n/a

**Comment by ThomasPiskol** [comment]
If you integrate #163 this issue will be fixed. I've tested the changes locally.

**Comment by hsks** [comment]
Would be lovely if someone could just merge it.

**Comment by joeykilpatrick** [comment]
@hsks Looks like it was merged, just hasn't been released. Hoping it will be released as 1.9.1 soon.

**Comment by hsks** [comment]
@joeykilpatrick  True. My bad. Waiting for it to be release soon 🤞 . Till then promisification of those functions should help.

**Comment by davidpatrick** [comment]
We are aiming at cutting a release for this today
