### ISSUE TITLE
connect ETIMEDOUT when trying to verify the token

### ISSUE THREAD

**Issue by xinghul** [auth0/node-jwks-rsa#165]
# Description
Here's the express middleware we used to verify the token:
```javascript
import * as jwt from 'express-jwt';
import * as jwksRsa from 'jwks-rsa';

import { config } from '../config';

const tokenVerifier = jwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: 'https://${config.authDomain}/.well-known/jwks.json',
  }),

  // Validate the audience and the issuer.
  audience: config.aspirexAuthAPIAudience,
  issuer: config.authIssuer,
  algorithms: ['RS256'],
});
```
It works fine locally, however, when we deployed it to production on GKE, sometimes we got this error:
```
connect ETIMEDOUT 54.201.13.236:443 { Error: connect ETIMEDOUT 54.201.13.236:443 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
url: 'https://xxx.auth0.com/.well-known/jwks.json',
```
Any idea why is this happening?

### Environment
- **Version of this library used: 1.9.0**
- **Version of the platform or framework used, if applicable: node v10.19.0**
- **Other modules/plugins/libraries that might be involved: express-jwt@6.0.0**

**Comment by davidpatrick** [comment]
Hey @xinghul while it's difficult to troubleshoot an inconsistent networking issue, there are a few things you could try here. How often do you receive the `ETIMEDOUT`?  Are there similarities on the IPs that it fails/succeeds on? You can view the [logs]( https://github.com/auth0/node-jwks-rsa/blob/e8196c93af01d57ed334a0fef51608633fdfdaa8/src/JwksClient.js#L35) for when it succeeds to see if there is some consistency with the IP that its succeeding on.  Where is the location of the deployed server vs when running local?

You could also try increasing the timeout when instating the library to see if that alleviates any issues.

```
const client = jwksClient({
  jwksUri: 'https://xxx.auth0.com/.well-known/jwks.json',
  timeout: 60000, // Defaults to 30s
});
```

**Comment by xinghul** [comment]
turns out I was running it in a private cluster, issue resolved.
