### ISSUE TITLE
use requestAgentOptions with ExpressJwtOptions / Typescript

### ISSUE THREAD

**Issue by mbs99** [auth0/node-jwks-rsa#167]
We're using version 1.9.0 with express and express-jwt
```
interface ClientOptions {
    jwksUri: string;
    rateLimit?: boolean;
    cache?: boolean;
    cacheMaxEntries?: number;
    cacheMaxAge?: number;
    jwksRequestsPerMinute?: number;
    proxy?: string;
    strictSsl?: boolean;
    requestHeaders?: Headers;
    timeout?: number;
  }
``` doens't include requestAgentOptions for configuring https certs. Can this be added?

**Comment by jarvisuser90** [comment]
I'm running into the same problem. We need this option so we can set our custom CA.

**Comment by jarvisuser90** [comment]
FYI: This is my workaround for the problem.

```javascript
// TODO: Temporary fix until "node-jwks-rsa" project adds native support for the requestAgentOptions property.
// Extend ExpressJwtOptions interface.
// Must extend BEFORE we use jwksRsa.expressJwtSecret.
declare module "jwks-rsa" {
  interface ExpressJwtOptions {
    requestAgentOptions?: AgentOptions;
  }
}

jwt({
  // Dynamically provide signing keys 
  // provided by the JWKS endpoint.
  secret: jwksRsa.expressJwtSecret({
    strictSsl: true,
    requestAgentOptions: {
      ca: fs.readFileSync(path.resolve(__dirname, "ca.crt"), "utf8")
    },
    cache: config.get("jwt.cache") as boolean,
    rateLimit: config.get("jwt.rateLimit") as boolean,
    jwksRequestsPerMinute: config.get("jwt.jwkRequestsPerMin") as number,
    jwksUri: config.get("jwt.jwkUri") as string
  }),
  audience: config.get("jwt.audience") as string,
  issuer: config.get("jwt.issuer") as string,
  algorithms: config.get("jwt.algorithms") as string[],
})
```

I hope this helps!

**Comment by davidpatrick** [comment]
Hey all, currently we are gating a lot of the agent options for the request, but what we are looking at doing is exposing the ability to completely override the agent used.

**Comment by lhargil** [comment]
> FYI: This is my workaround for the problem.
> 
> ```js
> // TODO: Temporary fix until "node-jwks-rsa" project adds native support for the requestAgentOptions property.
> // Extend ExpressJwtOptions interface.
> // Must extend BEFORE we use jwksRsa.expressJwtSecret.
> declare module "jwks-rsa" {
>   interface ExpressJwtOptions {
>     requestAgentOptions?: AgentOptions;
>   }
> }
> 
> jwt({
>   // Dynamically provide signing keys 
>   // provided by the JWKS endpoint.
>   secret: jwksRsa.expressJwtSecret({
>     strictSsl: true,
>     requestAgentOptions: {
>       ca: fs.readFileSync(path.resolve(__dirname, "ca.crt"), "utf8")
>     },
>     cache: config.get("jwt.cache") as boolean,
>     rateLimit: config.get("jwt.rateLimit") as boolean,
>     jwksRequestsPerMinute: config.get("jwt.jwkRequestsPerMin") as number,
>     jwksUri: config.get("jwt.jwkUri") as string
>   }),
>   audience: config.get("jwt.audience") as string,
>   issuer: config.get("jwt.issuer") as string,
>   algorithms: config.get("jwt.algorithms") as string[],
> })
> ```
> 
> I hope this helps!

I have encountered this problem as well. Currently building a Nestjs app.

Using your workaround, I can confirm that it works. Thank you.
