### ISSUE TITLE
Error when jwksUri is stored in a variable

### ISSUE THREAD

**Issue by sathyarajagopal** [auth0/node-jwks-rsa#181]
Hello,
I tried using jwks-rsa in my Node JS service and I am facing a strange issue. Details below:

**This doesn't work** 
const client = jwksClient({
    jwksUri: constant.JWKS_URL
  });
**This works**
  const client = jwksClient({
    jwksUri: 'https://abc.com/JWKS'
  });

If you take a closer look, the only difference is instead of hardcoding the URL, I tried placing the URL in a constant file and then consume it. But that doesn't work. Any idea?

**Comment by adamjmcgrath** [comment]
Hi @sathyarajagopal - thanks for sharing this

From that snippet, I can only conclude that `constant.JWKS_URL !== 'https://abc.com/JWKS'`

**Comment by sathyarajagopal** [comment]
@adamjmcgrath I have it as below:

const jw = require('../constant')
const client = jwksClient({
jwksUri: jw.JWKS_URL
});

It's strange that this doesn't work.

**Comment by adamjmcgrath** [comment]
Hi @sathyarajagopal - can you share your whole application (or at least the contents of `constant.js`) and the error message - it's difficult to help you with the information I have so far.

**Comment by sathyarajagopal** [comment]
Hi... The code works now. I couldn't trace the issue though.
