### ISSUE TITLE
Expose rsaPublicKeyToPEM util as part of public interface

### ISSUE THREAD

**Issue by jthomerson** [auth0/node-jwks-rsa#187]
### Describe the problem you'd like to have solved

In some cases I need the PEM version of my certificate after retrieving it as a JWK. Your library has a nice utility function (`rsaPublicKeyToPEM`) for doing this, but it's not available as part of the public API. This led to me needing a separate library ([rsa-pem-from-mod-exp](https://github.com/tracker1/node-rsa-pem-from-mod-exp/)) just for this. But that library has the same [Buffer deprecation issue](https://github.com/tracker1/node-rsa-pem-from-mod-exp/issues/4) that [this library had](https://github.com/auth0/node-jwks-rsa/issues/154) at one point.

I'd prefer to depend on Auth0's implementation of this, and avoid having duplicate code in my library. I was hoping you could expose a public utilities interface, perhaps similar to [how node-jose exposes utils](https://github.com/cisco/node-jose#useful-utilities).

### Describe the ideal solution

```ts
import rsaPublicKeyToPEM from 'jwks-rsa/utils';

const pem = rsaPublicKeyToPEM(jwk.n, jwk.e);
```

## Alternatives and current work-arounds

I have to use [rsa-pem-from-mod-exp](https://github.com/tracker1/node-rsa-pem-from-mod-exp/), resulting in duplicate code. I'd prefer to use Auth0's code because I trust Auth0 to be more active in the maintenance of this library since it's a core part of their business.

### Additional context

> Add any other context or screenshots about the feature request here.

N/A

**Comment by davidpatrick** [comment]
@jthomerson you can currently import this through `require('jwks-rsa/lib/utils')`, but just be aware that it's not supported as part of the SDK public api, so you might want to lock down a specific version if you plan to use it this way.

**Comment by jthomerson** [comment]
Ah, thanks @davidpatrick. Any chance adding utilities to the public API could be considered?
