### ISSUE TITLE
Upgrade axios dependency to latest verison

### ISSUE THREAD

**Issue by mikelax** [auth0/node-jwks-rsa#200]
### Describe the problem you'd like to have solved

The latest version of axios is currently `0.21.0`. This library should upgrade to the latest version of axios, assuming the plan is to stick with axios as opposed to switching to another library for making HTTP requests.

### Describe the ideal solution

Upgrade to axios version `0.21.0`

**Comment by davidpatrick** [comment]
Hey @mikelax if you have the time, PRs are welcome, otherwise I will get to this on our next release 👍

**Comment by davidpatrick** [comment]
@mikelax is there something you need from this axios `0.21.0` for this library? Or is this just a general dependency bump request?

**Comment by mikelax** [comment]
@davidpatrick at first I thought it was related to a snyk cve, but after double checking I don't see anything, so it can be considered a general bump. I did notice that version `0.20.0` seems to be a big change so maybe there will be a gain.

**Comment by lauriharpf** [comment]
@davidpatrick, #206 updates to `"axios": "^0.20.0"`, but should this issue still be kept open?

Doing an `npm init` to create an empty project and `npm add axios@^0.20.0` gives this warning:

> npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

Should we update to `axios@^0.21.1`?

**Comment by mikelax** [comment]
I agree, as long as we are upgrading the lib might as well go to the latest version and fix the cve.
