### ISSUE TITLE
ExpressJwtSecret is not a function in Typescript Project

### ISSUE THREAD

**Issue by dagmawim** [auth0/node-jwks-rsa#21]
It seems as tho in the index.d.ts file then constructor "expressJwtSecret" has been capitalized to "ExpressJwtSecret" which will compile fine but the underlying js call will not generate anything since the js resources do not have any variable named ExpressJwtSecret. Fix would be to rename the variable in the declaration file.

**Comment by mccool** [comment]
Until the pull request is merged you can get around it with `(jwksRsa as any).expressJwtSecret`

**Comment by sandrinodimattia** [comment]
This was released as 1.2.1 from #25
