### ISSUE TITLE
Coverage report included in NPM version 1.12.1

### ISSUE THREAD

**Issue by Bakerburgh** [auth0/node-jwks-rsa#210]
### Describe the problem
The latest NPM package (1.12.1) includes the coverage report output, causing the package size to be considerably larger.

### What was the expected behavior?
Installing this library using NPM should not include the coverage report in the node_modules folder. In other words, the following folder should not exist:
`./node_modules/jwks-rsa/coverage`

### Reproduction
Step 1: Install a particular version
Step 2: Check for the existence of `node_modules/jwks-rsa/coverage`

**Results:**
Version 1.11.0 is good:
```
MyPrompt$ npm i jwks-rsa@1.11.0
+ jwks-rsa@1.11.0
added 2 packages from 3 contributors and updated 3 packages in 3.084s

MyPrompt$ ls node_modules/jwks-rsa/coverage
ls: cannot access 'node_modules/jwks-rsa/coverage': No such file or directory
```

Version 1.12.0 is good:
```
MyPrompt$ npm i jwks-rsa@1.12.0
+ jwks-rsa@1.12.0
updated 1 package in 3.398s

MyPrompt$ ls node_modules/jwks-rsa/coverage
ls: cannot access 'node_modules/jwks-rsa/coverage': No such file or directory
```

Version 1.12.1 includes coverage reports:
```
MyPrompt$ npm i jwks-rsa@1.12.1
+ jwks-rsa@1.12.1
removed 2 packages and updated 3 packages in 3.141s

1 package is looking for funding
  run `npm fund` for details

MyPrompt$ ls node_modules/jwks-rsa/coverage
lcov-report/  lcov.info
```

### Environment
- **Version of this library used:**
1.12.1
- **Which framework are you using, if applicable:**
npm
- **Other modules/plugins/libraries that might be involved:**
none
- **Any other relevant information you think would be useful:**
Windows, using Git Bash

**Comment by davidpatrick** [comment]
Thanks @Bakerburgh let me get this fixed uup

**Comment by davidpatrick** [comment]
Fixed in https://github.com/auth0/node-jwks-rsa/releases/tag/v1.12.2
