### ISSUE TITLE
@types/express as runtime dependency instead of devDependencies

### ISSUE THREAD

**Issue by samuelmesq** [auth0/node-jwks-rsa#211]
### Describe the problem

`@types/express` back as a runtime dependency instead of devDependencies.

### What was the expected behavior?

not have `@types/express` installed when install jwks-rsa?

### Environment

- **Version of this library used:** 1.12.1
- **Which framework are you using, if applicable:** Hapi
- **Other modules/plugins/libraries that might be involved:** hapi-auth-jwt2
- **Any other relevant information you think would be useful:** There is a related issue https://github.com/auth0/node-jwks-rsa/issues/58

Thanks :)

**Comment by adamjmcgrath** [comment]
Hey @samuelmesq 

We're happy with it being in `devDependecies`, we don't re-export any express types and we work under the assumption that if you're creating an express app with typescript you'll have `@types/express` installed.

In cases where you're not using express (I see you're using Hapi), you'll have to install `@types/express` yourself

**Comment by samuelmesq** [comment]
Hi @adamjmcgrath, it's the same thing on https://github.com/auth0/node-jwks-rsa/issues/58, if you look in the current release @types/express is place at "dependencies" instead of "devDependencies" https://github.com/auth0/node-jwks-rsa/blob/master/package.json#L8. 

It's not a bug, everything is working, but it's installing unnecessary types.

**Comment by charsleysa** [comment]
@adamjmcgrath To expand on what @samuelmesq reported, currently any project that does not utilize `express` must still install the `@types/express-jwt` and `@types/express` packages (this is done implicitly be NPM) which increases npm install times and adds unnecessary bloat.

`@types/express-jwt` should be considered an optional peer dependency instead of a required dependency as it is only useful to those who use `express`.

**Comment by davidpatrick** [comment]
There has been some back n forth on this in the past, but it was decided here https://github.com/auth0/node-jwks-rsa/pull/80#pullrequestreview-244880314 that this should be a regular dependency.

The import here https://github.com/auth0/node-jwks-rsa/blob/master/index.d.ts#L1 also makes it a requirement, regardless of usage with express-jwt. You can see it failing here when I try to use the module without it as the dependency
![image](https://user-images.githubusercontent.com/1422227/109065529-944f4500-76a0-11eb-8a9b-3611cf2cd75f.png)
