### ISSUE TITLE
1.12.2 tag/version doesn't match source

### ISSUE THREAD

**Issue by PeterJakubik** [auth0/node-jwks-rsa#223]
Hi
I'm using version latest 1.12.2 but the code doesn't contain latest changes from master.
In master in express.js in master there is a check for algorithm range https://github.com/auth0/node-jwks-rsa/blob/596e944357b8c7c11c1f73890e4982f45e734cbf/src/integrations/express.js#L26 but in 1.12.2 there is still old version checking only for RS256 algorithm

In master 
```javascript
if (!header || header.alg !== 'RS256') { 
```

Last commit to master was on 7 Jan but the Release 1.12.2 on 8 Jan doesn't contain those changes

**Comment by davidpatrick** [comment]
Hi @PeterJakubik we haven't yet cut a release since merging https://github.com/auth0/node-jwks-rsa/pull/205.  This will be a major release, and introduce some breaking changes.  We have had some priorities shift around over last 2 weeks, but now we are working on getting a release out this week.
