### ISSUE TITLE
Update typescript definition for 2.0.0 release

### ISSUE THREAD

**Issue by mlegenhausen** [auth0/node-jwks-rsa#228]
### Describe the problem

The typescript definition are not aligned with the new callback free implementation in release 2.0.0

### What was the expected behavior?

Working typescript definitions.

### Environment

- **Version of this library used: 2.0.0**
- **Which framework are you using, if applicable: typescript@4.1.5**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by itajaja** [comment]
took a stab here https://github.com/auth0/node-jwks-rsa/pull/230
