### ISSUE TITLE
Signing Keys empty when "use": "sig" field not provided

### ISSUE THREAD

**Issue by BartKrol** [auth0/node-jwks-rsa#24]
My auth provider stores keys in a following format:
```json
{
  "keys": [{
    "kty": "RSA",
    "kid": "XXX",
    "n": "XXX",
    "e": "XXX"
  }]
}
```

As you can see, it's missing `use` param. According to [JWK RFC](https://tools.ietf.org/html/rfc7517#section-4.2) this param is:
> OPTIONAL, unless the application requires its presence.

To be honest I have difficulties to interpret this part. The bottom line is that I cannot make it work with my auth provider, because of this line:
https://github.com/auth0/node-jwks-rsa/blob/master/src/JwksClient.js#L52

Would it be possible to make `use` param optional?

**Comment by BartKrol** [comment]
Any updates on this one :)?

**Comment by gap777** [comment]
Updates or workarounds?

**Comment by gap777** [comment]
This is still an issue.... help??

**Comment by manpreet-compro** [comment]
This is still an issue. We should check only if 'use' key is present and has non-blank value. I can provide a pull request.
