### ISSUE TITLE
Bump Jose to fix getCurves bug

### ISSUE THREAD

**Issue by thesiti92** [auth0/node-jwks-rsa#243]
### Describe the problem

because of this issue https://github.com/panva/jose/issues/72, using this package to auth in a Cloudflare Worker doesnt work since it's not a native node environment and polyfills dont work for some reason.

Seems like bumping the jose version to post v3 would fix it!

### Reproduction

Try to get signing keys using a simple jwks client in a cloudflare worker

### Environment

- **Version of this library used:** 2.0.2
- **Which framework are you using, if applicable:** Cloudflare Worker
- **Other modules/plugins/libraries that might be involved:** Jose
- **Any other relevant information you think would be useful:**

**Comment by panva** [comment]
> `fix getCurves bug`

There is no such "bug". `jose` below v3.x was a node package where other runtimes were simply not supported. The same can be said for `jwks-rsa`.

**Comment by thesiti92** [comment]
ok so call it a feature then... if bumping one package would make it universal and let it support workers then that should be worth it, no?

**Comment by panva** [comment]
> ok so call it a feature then... if bumping one package would make it universal and let it support workers then that should be worth it, no?

It is unfortunately not that simple. We have to consider the node runtime support matrix for the recently released major. Bumping jose also isn't as simple as changing the version number. It's an entirely new API.

**Comment by panva** [comment]
FYI you may want to give [`jose/jwks/remote`](https://github.com/panva/jose/blob/main/docs/functions/jwks_remote.createremotejwkset.md#readme) a try if you believe its browser runtime will work in cloudflare workers which IIRC is neither node, nor purely browser.

**Comment by thesiti92** [comment]
ah ok will check it out, ty. and yeah i read through some of the code and the dependence on jose didnt seem super high from my naive first glance, but yeah if the new version changes the whole api then i totally get that. thanks again

**Comment by sgammon** [comment]
@panva why is this bug closed? This package still doesn't support Cloudflare Workers...

**Comment by panva** [comment]
@sgammon please try and provide more context. `jose` works natively in CF Workers and AFAIK `jwks-rsa` needed `node:crypto` APIs are also part of the CF Workers API.

FWIW this is a Node.js package so your mileage may vary.

A pure `jose` way of verifying tokens using remote jwks is also available.
```
import * as jose from 'jose'

const JWKS = jose.createRemoteJWKSet(new URL('https://www.googleapis.com/oauth2/v3/certs'))

const { payload, protectedHeader } = await jose.jwtVerify(jwtToken, JWKS, {
  issuer: 'urn:example:issuer',
  audience: 'urn:example:audience',
})
```
