### ISSUE TITLE
getKeysInterceptor in typescript is not working.

### ISSUE THREAD

**Issue by GeorgeMickael** [auth0/node-jwks-rsa#246]
The return type of getKeysInterceptor()  in typescript is Promise<SigningKey[]>. The type 'SigningKey' does not accept at keys array read from json file.  
 
### What was the expected behavior?

getKeysInterceptor() should accept array of keys or there should be a utility function provided to convert the array of keys to required type that getKeysInterceptor() needs.

### Environment
Typescript  4.1.3
"jwks-rsa": "^2.0.2"

**Comment by davidpatrick** [comment]
Hey @GeorgeMickael thanks for pointing this out, the middleware does have a utility to convert the array https://github.com/auth0/node-jwks-rsa/blob/master/src/wrappers/interceptor.js#L11-L16, but the type is tied to the `getKeysInterceptor` func and not the middleware.  I will get a fix for the typedef out, thanks
