### ISSUE TITLE
"TypeError: jwks_rsa_1.default is not a function"

### ISSUE THREAD

**Issue by mikejtaylor22** [auth0/node-jwks-rsa#250]
### Describe the problem
Getting "TypeError: jwks_rsa_1.default is not a function" when trying to verify a JWT against a public key (RS256)

When trying to use the following code, I get "TypeError: jwks_rsa_1.default is not a function"

import jwksClient from "jwks-rsa";

  const client = jwksClient({
      jwksUri: "https://api.com/my/url",
    });

### What was the expected behavior?

> to reach out to the provided uri and get information on the public Keys

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

> Where possible, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - Screenshots
-->

- Step 1..

### Environment

- "jwks-rsa": "^2.0.3",
- Nestjs/Typescript

**Comment by davidpatrick** [comment]
@mikejtaylor22 this is covered on https://github.com/auth0/node-jwks-rsa/issues/78 you'll need to use `esModuleInterop` in your `tsconfig.json` or `import * as jwks from "jwks-rsa"`

**Comment by mikejtaylor22** [comment]
> @mikejtaylor22 this is covered on https://github.com/auth0/node-jwks-rsa/issues/78 you'll need to use `esModuleInterop` in your `tsconfig.json` or `import * as jwks from "jwks-rsa"`

Hmm I tried both of these but neither seemed to work. I set esModuleInterop to true in tsconfig and did that import. Also tried using jwksRsa and jwksClient both of them threw the not a function error
