### ISSUE TITLE
Allow jwksUri to be resolved by a provider

### ISSUE THREAD

**Issue by uwinkelvos** [auth0/node-jwks-rsa#252]
### Describe the problem you'd like to have solved
I work with a stack in which the actual `jwksUri` is not static, but needs to be fetched from different endpoints depending on parts of the payload (e.g. issuer claim). 

### Describe the ideal solution
If instead of a string the `jwksUri` could be given as a provider the use-case would be covered:
```
jwksUri: string | (jwtHeader, jwtPayload) => Promise<string>
```
Unfortunately this would mean that the api of `JwksClient` would break as the whole payload and header would need to be passed in every method instead of only kid. 

## Alternatives and current work-arounds
unfortunately none that i can think of.

### Additional information, if any
I would be up for implementing this and provide a PR, but wanted to clarify if the use case should actually be covered by this library, or if we should rather fork.

**Comment by adamjmcgrath** [comment]
Hi @uwinkelvos - I don't think this sdk could ever let you trust the payload of a JWT until it's signature has been verified (which it would need the `jwksUri` for)

You will probably need to fork, unless you can pick the `jwksUri` from some other part of the request?

**Comment by adamjmcgrath** [comment]
Actually, you could also check out https://github.com/auth0/node-jwks-rsa/issues/49#issuecomment-421662283

**Comment by uwinkelvos** [comment]
> Actually, you should check out [#49 (comment)](https://github.com/auth0/node-jwks-rsa/issues/49#issuecomment-421662283)
Thanks, that is actually pretty similar to our case, although our issuer urls are not static. Therefore we actually have to cache a client per issuer instead of the singleton approach in #49, but that works aswell.
