### ISSUE TITLE
update `jose` dependency to the latest

### ISSUE THREAD

**Issue by vladkasianenko** [auth0/node-jwks-rsa#258]
C:\Users\S8PHUD\source\repos\my-project-name\server>npm ls jose
my-project-name@1.0.0 C:\Users\S8PHUD\source\repos\my-project-name\server
└─┬ jwks-rsa@2.0.4
  └── jose@2.0.5

And the Aqua Scanner:
![image](https://user-images.githubusercontent.com/14053728/130087833-e4b13fce-e876-426e-b697-b6f72bcb349a.png)

**Comment by adamjmcgrath** [comment]
Hi @vladkasianenko - thanks for raising this

Those CVEs are for the `jose-browser-runtime`, `jose-node-esm-runtime` and `jose-node-cjs-runtime` packages respectively.

The vulnerability was patched in the version we use (`jose@2.0.5` - which is the latest `2.x` release) so does not affect this project.

It looks like "Aqua Scanner" (or the registry it's using) is incorrectly attributing those vulnerabilities to the `jose` package

**Comment by vladkasianenko** [comment]
@adamjmcgrath 
Well, yeah, make sense.
