### ISSUE TITLE
Possible memory leak in current usage of the debug lib for logging

### ISSUE THREAD

**Issue by josmo** [auth0/node-jwks-rsa#266]
### Describe the problem

When using the library in nestjs via express we're finding the that when create a new instance of jwks on the requests it won't GC the debug lib logging inside.
ie
```
const client = jwks({
   cache: true,
   cacheMaxEntries: 5,
   cacheMaxAge: 36000000,
    jwksUri,
 });
```

and overtime will crash with OOM :(

### What was the expected behavior?

not create a new instance of the debug logger each time.

### Reproduction
For next JS creating a passport strategy where on validate we create the above client. We'll see the memory usage increase over time.

### Environment

version: jwks-rsa: "^2.0.3"
Framework: nestjs with passport

###

I believe having the following change would remove the constant creation of a new logger out of the class although I'm totally open to a different solution.

https://github.com/josmo/node-jwks-rsa/commit/066f1a511f23564bdf1464bbe987c44ff40720c2

src/JwksClient.js is where I believe the issue lies, but I also changed the rest to be consistent.

If this seems reasonable I can open the PR for it right away.

Thanks! :)

**Comment by adamjmcgrath** [comment]
Hi @josmo - happy to accept josmo@066f1a5 as a PR, looks like a more idiomatic use of `debug`

> where on validate we create the above client

Although, you shouldn't be creating a new JWKS Client on each request, a single client should be shared between requests so you can benefit from the `jwks.json` cache

**Comment by josmo** [comment]
Thanks @adamjmcgrath totally makes sense for using shared client to get use from the JWKS cache :)

I'll still submit the PR since it's more idiomatic anyways :)

**Comment by adamjmcgrath** [comment]
Thanks @josmo!
