### ISSUE TITLE
Request timeout doesn't work properly

### ISSUE THREAD

**Issue by amrsalama** [auth0/node-jwks-rsa#270]
### Describe the problem

- `JwksClient` accepts a `timeout` option and by default has a value of 30 sec, but actually this value doesn't have a real effect, if the request reaches the timeout it won't be destroyed.
- The issue happens because we don't listen on the `timeout` event that is emitted by the request as stated by the docs https://nodejs.org/api/http.html#http_event_timeout
- Similar issue with `http` timeout option can be found here https://github.com/nodejs/node/issues/12005

### What was the expected behavior?

- The request to be destroyed when it reaches the specified timeout value.

### Environment

- **Version of this library used:** 2.0.4

**Comment by adamjmcgrath** [comment]
Hi @amrsalama - will get released when #272 is merged

**Comment by amrsalama** [comment]
@adamjmcgrath Thanks a lot!
