### ISSUE TITLE
Integration with Hapi-auth-jwt2 and Auth0 returns "Invalid Token"

### ISSUE THREAD

**Issue by dankell** [auth0/node-jwks-rsa#273]
### Describe the problem

The Auth0 Node.js example uses Express.js and jwks-rsa to authenticate an Auth0 token using jwt.
The example for Hapi(https://github.com/auth0/node-jwks-rsa/tree/master/examples/hapi-demo) uses the syntax for an old version of Hapi, and when the settings from the Express.js example are integrated into a working jwt server the server fails to validate the supplied token.

### What was the expected behavior?

Accessing the server with an Auth0 token should return a valid response.

### Reproduction
```
const Hapi = require('@hapi/hapi')
const jwt = require('hapi-auth-jwt2')
const jwksRsa = require('jwks-rsa')

const validate = async (decoded) => {
  return { isValid: true }
}

const init = async () => {
  const server = new Hapi.server({ port: 8000 })
  await server.register(jwt)
  server.auth.strategy('jwt', 'jwt', {
    complete: true,
    headerKey: 'authorization',
    tokenType: 'Bearer',
    secret: jwksRsa.hapiJwt2Key({
      cache: true,
      rateLimit: true,
      jwksRequestsPerMinute: 5,
      jwksUri: 'https://[my.Auth0.details]/.well-known/jwks.json'
    }),
    // Your own logic to validate the user.
    validate,
    verifyOptions: {
      audience: 'https://[my.Auth0.details],
      issuer: 'https://[my.Auth0.details]/',
      algorithms: ['RS256']
    }
  })
  server.auth.default('jwt')
  server.route([
    {
      method: 'GET',
      path: '/',
      config: {
        auth: false
      },
      handler: () => ({ text: 'Token not required' })
    },
    {
      method: 'GET',
      path: '/restricted',
      config: {
        auth: 'jwt'
      },
      handler: (request, h) => {
        const response = h.response({ text: 'You used a token' })
        response.header('Authorization', request.headers.authorization)
        return response
      }
    }
  ])
  await server.start()
  return server
}
```
### Environment
    "@hapi/hapi": "^20.2.1",
    "hapi-auth-jwt2": "^10.2.0",
    "jwks-rsa": "^2.0.5"

**Comment by adamjmcgrath** [comment]
Hi @dankell 

> secret: jwksRsa.hapiJwt2Key({

You need to change this to `key: jwksRsa.hapiJwt2KeyAsync({`

**Comment by dankell** [comment]
Perfect. Thank you. 
Now I just need to figure out how to interrogate the Token and confirm that the credentials are correct. 
But at least I am now getting the Token decoded.

If I was to try and rewrite the Hapi example to a working version, would that be a useful submission?

**Comment by adamjmcgrath** [comment]
> If I was to try and rewrite the Hapi example to a working version, would that be a useful submission?

Sure, that would be great thanks
