### ISSUE TITLE
koaJwtSecret Typescrypt typing

### ISSUE THREAD

**Issue by jerep6** [auth0/node-jwks-rsa#28]
Hi,

I don't understand the signature of koaJwtSecret.

In the file *index.d.ts* the koaJwtSecret definition is:
```javascript
function koaJwtSecret(options: JwksRsa.Options): (name: string, scheme: string, options?: any) => void;
```
but the code in *lib/integrations.ts* doesn't match this signature. It return the function *[secretProvider](https://github.com/auth0/node-jwks-rsa/blob/master/src/integrations/koa.js#L12)* that:
 * take one argument : the header of the token to extract "alg" and "kid"
 * return a string and not void: the public key or  the rsa public key 

I think the signature should be:
```javascript
function koaJwtSecret(options: JwksRsa.Options): (header: object) => Promise<string>;
```

Is it an error or didn't understand?

**Comment by samuela** [comment]
Yes, documentation please!
