### ISSUE TITLE
Explicitly list the algorithms this supports, e.g. RS256, RS384, RS512

### ISSUE THREAD

**Issue by marvin1up** [auth0/node-jwks-rsa#281]
### Describe the problem you'd like to have solved
Documentation only.

 I haven't looked in the code but it seems by the library name that this would support getting signing keys as long as the `alg` is one of `RS256`, `RS384` or `RS512`
 
 In one documentation example, there is a setting of `alg: "RS256"` suggesting that is supported.  
 
### Describe the ideal solution
Add a sentence in the readme that the three algorithms `RS256`, `RS384` or `RS512` are supported (or, whatever set of `alg` values would work.)

## Alternatives and current work-arounds
None

### Additional information, if any
None

**Comment by marvin1up** [comment]
OK, and I looked at the code, and find `allowedSignatureAlg` in `config.js` - so presumably this package jwks-rsa actually supports getting signing keys and there public key data for other algorithms besides "RSA" algorithms.  It's worth a sentence in the README, maybe?

**Comment by kcmannem** [comment]
+1, on first notice its not obvious the library supports more than rsa
