### ISSUE TITLE
Please document logging verbosity

### ISSUE THREAD

**Issue by ninapavlich** [auth0/node-jwks-rsa#282]
### Describe the problem you'd like to have solved

I am encountering an issue when I call `getSigningKey` where an error is thrown with limited information; the object returned is simply this: ` {"name":"JwksError","message":"Found"}`

Since this error is too limited to troubleshoot, it would be helpful to see the output of the various logger() statements ([such as this one](https://github.com/auth0/node-jwks-rsa/blob/bc05ccc70126db9c10c022e804af4c3e262a4b70/src/JwksClient.js#L47))

### Describe the ideal solution

Is there a way to either initialize the JwksClient with a certain logging verbosity? Or alternately an environment variable I can set to see this output?

## Alternatives and current work-arounds

Alternatively an error-message reference table to give more background on what this error message means would be helpful too.

### Additional information, if any

Thanks for your help!

**Comment by adamjmcgrath** [comment]
Hi @ninapavlich - thanks for raising this

Please take a look at https://github.com/auth0/node-jwks-rsa#showing-trace-logs which should describe what you need

Any other questions or if you want to reopen this feel free to ping me
