### ISSUE TITLE
Unnecessary dependency @types/express-jwt

### ISSUE THREAD

**Issue by steelerc69** [auth0/node-jwks-rsa#286]
### Describe the problem
When packaging solution, @types/express-jwt is included, but all @types are dev dependencies and do not need to be bundled for deployment.  This primarily becomes an issue when deploying code to AWS lambda or other areas where there is a limit on package size and every byte matters.

### What was the expected behavior?
@types/express-jwt is moved to dev-dependencies

### Environment
current version

**Comment by adamjmcgrath** [comment]
Hi @steelerc69 - there's been some back and forth on this. In the end we decided to stick to it in dependencies - See https://github.com/auth0/node-jwks-rsa/pull/80#pullrequestreview-244880314
