### ISSUE TITLE
SSL Error: X.jwks.json does not support SSL

### ISSUE THREAD

**Issue by TheFastCat** [auth0/node-jwks-rsa#29]
Hey guys I get this when pointing to my Auth0 jwks file:

https://{my tenant}.auth0.com/.well-known/jwks.json

I realize that there is an option to override this error - but why is it happening? The Auth-0 endpoint is https, isn't it? Is it generating the error from my dev server? If so the message is misleading.

**Comment by nielmistry** [comment]
It's happening to me too, don't know why

**Comment by artemave** [comment]
This pr offers a workaround #60

**Comment by damntourists** [comment]
I'm having this issue as well. It's been almost two years since this was reported. Any official fix on the horizon?

**Comment by Somebi** [comment]
same problem here
