### ISSUE TITLE
express-jwt integration issues with new v7

### ISSUE THREAD

**Issue by alechartung** [auth0/node-jwks-rsa#296]
I have a project mostly following the [express example](https://github.com/auth0/node-jwks-rsa/tree/master/examples/express-demo), and having issues after upgrading to [express-jwt](https://github.com/auth0/express-jwt) 7.4.3.

> TypeError: cb is not a function

Haven't looked too deeply yet, could be just the example needs updating.

Thanks!

**Comment by nsshunt** [comment]
Yes I have same problem and the function sig from the returned function from expressJwtSecret is broken.

I was told to use this instead;

const expressJwtSecret = function (options) {
			if (options === null || options === undefined) {
			  throw new ArgumentError('An options object must be provided when initializing expressJwtSecret');
			}
		  
			const client = new jwksRsa.JwksClient(options);
			const onError = options.handleSigningKeyError || handleSigningKeyError;
		  
			return function secretProvider(req, token) {
			  const { header } = token;
			  if (!header || !supportedAlg.includes(header.alg)) {
				return;
			  }
			  return client.getSigningKey(header.kid)
				.then(key => {
				  return key.publicKey || key.rsaPublicKey;
				}).catch(err => {
				  return new Promise((resolve, reject) => {
					onError(err, (newError) => reject(newError));
				  });
				});
			}

However, this also does not work (mine times out when trying to find scopes).

So the "integration" between the two modules is broken. Go back to 6.1.2 until both are fixed.

**Comment by trasherdk** [comment]
```js
const expressJwtSecret = function (options) {
  if (options === null || options === undefined) {
    throw new ArgumentError('An options object must be provided when initializing expressJwtSecret');
  }

  const client = new jwksRsa.JwksClient(options);
  const onError = options.handleSigningKeyError || handleSigningKeyError;

  return function secretProvider (req, token) {
    const { header } = token;
    if (!header || !supportedAlg.includes(header.alg)) {
      return;
    }
    return client.getSigningKey(header.kid)
      .then(key => {
        return key.publicKey || key.rsaPublicKey;
      }).catch(err => {
        return new Promise((resolve, reject) => {
          onError(err, (newError) => reject(newError));
        });
      });
  }
}
```
