### ISSUE TITLE
Fix: Types error Cannot find namespace 'Express'

### ISSUE THREAD

**Issue by BismitaRath** [auth0/node-jwks-rsa#305]
### Describe the problem

There was a recent patch release for types change in index.d.ts file, which is causing `error TS2503: Cannot find namespace 'Express'`.
[https://github.com/auth0/node-jwks-rsa/blob/master/index.d.ts#L69:L70](url)

### What was the expected behavior?
Needs  to add the required library  for `Express` namespace type.

### Environment

- **Version of this library used: V2.1.1**

**Comment by adamjmcgrath** [comment]
Hi @BismitaRath - this should be fixed in https://github.com/auth0/node-jwks-rsa/releases/tag/v2.1.2
