### ISSUE TITLE
Fix: Typescript error Module can only be default-imported using the 'esModuleInterop' flag

### ISSUE THREAD

**Issue by nickgvt** [auth0/node-jwks-rsa#309]
### Describe the problem

There was a recent patch release for types change in index.d.ts file, which is causing as error:
```
TS 1259: Module '"/node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag
4 import Express from 'express'
         ~~~~~~~

  node_modules/@types/express/index.d.ts:133:1
    133 export = e;
        ~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```

This seems to be related to  https://github.com/auth0/node-jwks-rsa/issues/305

### Expected behavior

I would like to be able to build my project without needing to add a typescript flag and change all my existing imports

### Reproduction

This tsconfig file looks like this
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES2019",
    }
}
```
### Environment

* jwks-rsa v 2.1.2
*  typescript  4.x
* node 16

**Comment by maplesteve** [comment]
Our builds are also failing since v2.1.2 due to the change in #305.

**Comment by kirillgroshkov** [comment]
Same for us. Pinned to `2.1.1` until it's fixed.
