### ISSUE TITLE
Let's update the jose dependency

### ISSUE THREAD

**Issue by revelt** [auth0/node-jwks-rsa#313]
### Describe the problem you'd like to have solved

I'm raising a reminder ticket to nudge maintainers to bump the `jose` dependency which is now two major versions behind.

It was raised before, in issues #285, #279, #262, #258 and #243.

### Describe the ideal solution

As a bonus, hopefully it will solve the "getCurves is not a function" errors.

**Comment by adamjmcgrath** [comment]
Hi @revelt - thanks for raising this

The latest version of `jose` does not have compatible Node.js support for this SDK so we don't currently have any plans to update it. If/when we consider a new major for this SDK, we'll address the `jose` dependency.
