### ISSUE TITLE
Please document cacheMaxAge and jwksRequestsPerMinute

### ISSUE THREAD

**Issue by Aaronius** [auth0/node-jwks-rsa#324]
### Describe the problem you'd like to have solved
The `cacheMaxAge` and `jwksRequestsPerMinute` options could be better documented.

### Describe the ideal solution
Please document `cacheMaxAge` and `jwksRequestsPerMinute` under _JwksClient Options_. For `cacheMaxAge`, please explicitly define what unit the value is in (milliseconds?).

**Comment by adamjmcgrath** [comment]
Thanks for raising this @Aaronius - raised #327
