### ISSUE TITLE
expressJwtSecret can return undefined which is not reflected in GetVerificationKey type

### ISSUE THREAD

**Issue by AaronMoat** [auth0/node-jwks-rsa#328]
### Describe the problem

`expressJwtSecret` in the `GetVerificationKey` mode can return a `Promise` of `undefined`, e.g. here:

```
    if (!token) { return; }
```

but `GetVerificationKey` returns `Secret | Promise<Secret>` to which undefined or Promise<undefined> are not assignable.

### What was the expected behavior?

The typing for `GetVerificationKey` should include `undefined`.

### Reproduction

This fails to compile:

```
const x: Awaited<ReturnType<GetVerificationKey>> = undefined;
```

### Environment

- **Version of this library used:**: 2.1.4

**Comment by adamjmcgrath** [comment]
Hi @AaronMoat - thanks for raising this

`GetVerificationKey` should either [return a key](https://github.com/auth0/node-jwks-rsa/blob/master/src/JwksClient.js#L81) or [throw an error](https://github.com/auth0/node-jwks-rsa/blob/master/src/JwksClient.js#L84)

It shouldn't be possibly to return any falsey value for `key` - so the types look ok to me
