### ISSUE TITLE
getKeyInterceptor in express integration

### ISSUE THREAD

**Issue by nhomble** [auth0/node-jwks-rsa#336]
### Describe the problem you'd like to have solved

I want to know when my app is reaching out to the jwks uri vs pulling from a cache.

### Describe the ideal solution

The express options expose callback hooks around the jwk call. 

## Alternatives and current work-arounds

I considered setting the environment variable to get the trace logs as described here: https://github.com/auth0/node-jwks-rsa/blob/master/EXAMPLES.md#showing-trace-logs

But creating the logs through my own logger (via winston) would allow me to control the format. This is helpful for teams like mine where logging needs to be in a json format. 

### Additional information, if any

I was thinking of using the interceptor described here: https://github.com/auth0/node-jwks-rsa/blob/master/EXAMPLES.md#loading-keys-from-local-file-environment-variable-or-other-externals

But I don't see an equivalent for folks using the express integration

**Comment by adamjmcgrath** [comment]
Hi @nhomble - thanks for raising this

> I was thinking of using the interceptor ...
> But I don't see an equivalent for folks using the express integration

The options that the `JwksClient` are the same as the options you pass `expressJwtSecret` - so you can use the `getKeysInterceptor` in the express integration like so:

```js
const app = new Express();
app.use(jwt({
  secret: jwksRsa.expressJwtSecret({
    // ...
    getKeysInterceptor: () => {}
  }),
  // ...
}));
```

**Comment by nhomble** [comment]
@adamjmcgrath thanks and sorry for the miss on my side.

**Comment by nhomble** [comment]
For posterity, I went ahead with a different approach. After upgrading to a newer version of the library that uses `http` for jwk refresh, I was able to use datadog's out-of-the-box tracer plugin to get the observability I wanted without the custom interceptor.
