### ISSUE TITLE
Types for JwksClient.getSigningKey still allows callbacks

### ISSUE THREAD

**Issue by tstackhouse** [auth0/node-jwks-rsa#353]
### Describe the problem

When 2.0.0 was released, `getSigningKey` was updated to no longer allow callbacks and be purely promise/async based, however even in 3.0.1 the type declaration for `getSigningKey` allows for the callback form, therefore it will not flag a TypeScript error upon upgrading from versions < 2.0.0.

### What was the expected behavior?

Provided typings accurately reflect the available behaviour of the library.

### Reproduction

1. Call getSigningKey using a version of the library < 2.0.0
2. Upgrade to any version >= 2.0.0
3. TypeScript compilation/IDEs do not report anything wrong, but code will fail at runtime

### Environment

- **Version of this library used:** 1.9.0 -> 3.0.1
- **Which framework are you using, if applicable:** Node 16
- **Other modules/plugins/libraries that might be involved:** AWS Lambda
- **Any other relevant information you think would be useful:** N/A

**Comment by adamjmcgrath** [comment]
Hi @tstackhouse - thanks for raising this

Callback support was added back to `getSigningKey` in 2.0.1 (see https://github.com/auth0/node-jwks-rsa/blob/master/CHANGELOG.md#201---2021-03-12)

You can test this yourself doing

```sh
$ node -e "new (require('jwks-rsa').JwksClient)({}).getSigningKey(null, () => {console.log('callback fired');})"
callback fired
```

**Comment by tstackhouse** [comment]
I see! I missed that.  That said, at least in the `master` branch, it seems like the callback form of `getSigningKey` is not present in the code: https://github.com/auth0/node-jwks-rsa/blob/master/src/JwksClient.js#L52-L67
