### ISSUE TITLE
Types conflict between jwks-rsa@3.0.1 and express-jwt@8.4.1

### ISSUE THREAD

**Issue by threes-was-taken** [auth0/node-jwks-rsa#356]
### Describe the problem

Using `express-jwt@8.4.1` and `jwks-rsa@3.0.1`, I came across a similar issue described in #299. 

Following ts error is described by my IDE (vs-code)
``` 
Type 'SecretCallbackLong | GetVerificationKey' is not assignable to type 'Secret | GetVerificationKey'.
Type 'SecretCallbackLong' is not assignable to type 'Secret | GetVerificationKey'.
Type 'SecretCallbackLong' is not assignable to type 'GetVerificationKey'.
```

For expected behaviour and reproduction steps, please refer to #299 as they are the same in my case.

### Environment

- **Version of this library used:** 3.0.1
- **Which framework are you using, if applicable:** Express
- **Other modules/plugins/libraries that might be involved:** express-jwt@8.4.1
- **Any other relevant information you think would be useful:**

**Comment by senputra** [comment]
You can downgrade your `express-jwt` to `^6.1.0` at the meantime.

**Comment by adamjmcgrath** [comment]
Hi @threes-was-taken - thanks for raising this. This is an issue with express-jwt, please use the workaround described in https://github.com/auth0/express-jwt/issues/288#issuecomment-1122524366
