### ISSUE TITLE
The JWKS endpoint did not contain any signing keys

### ISSUE THREAD

**Issue by hmalhi** [auth0/node-jwks-rsa#360]
### Describe the problem

Getting error running the samplee code provided in introduction
The JWKS endpoint did not contain any signing keys

### What was the expected behavior?

Should have been able to read the keys from jwks.json

### Reproduction
Run the example code given
const jwksClient = require("jwks-rsa");

const client = jwksClient({
  jwksUri: "https://sandrino.auth0.com/.well-known/jwks.json",
  requestHeaders: {}, // Optional
  timeout: 30000 // Defaults to 30s
});

const kid = "RkI5MjI5OUY5ODc1N0Q4QzM0OUYzNkVGMTJDOUEzQkFCOTU3NjE2Rg";
const key = client.getSigningKey(kid);
console.log(key);

### Environment

version 3.0.1

**Comment by adamjmcgrath** [comment]
HI @hmalhi - the `jwksUri` should be a fully qualified URL (https://sandrino.auth0.com/.well-known/jwks.json)
