### ISSUE TITLE
Add pre-fetch keys / tweaks to caching

### ISSUE THREAD

**Issue by jmaxxz** [auth0/node-jwks-rsa#362]
### Describe the problem you'd like to have solved

Currently the JWKS client only caches keys based on a `kid`  via the getSigningKey key function. The mechanism by which getSigningKey works is to get all the keys in the discovery endpoint and then to filter that list down to just the requested key. 

The network request to get all the keys is the expensive bit of the operation, the filtration is more or less free. Yet the cache is only seems to cache the specific key that was asked for. 

See:
https://github.com/auth0/node-jwks-rsa/blob/master/src/JwksClient.js#L71
https://github.com/auth0/node-jwks-rsa/blob/master/src/wrappers/cache.js

Additionally, the current default cache size is 5 keys, this seems rather small as a default. Looking my AAD tenant I see it currently has 8 signing keys, so the default of 5 would cause a lot of cache churn. It would seem to me that a default limit of ~30 would make more sense, as IMO most users should not really have to know or care about this parameter.

### Describe the ideal solution

I would like to make a change so that getSigningKeys()  is cached. This would allow prefetching all currently known keys without having to know the/a `kid`.

In the event getSigningKey(kid) is called and key is not in cache, it is debatable what should be done. A strategy might be to call a uncached version  of getSigningKeys() and rely on the current caching mechanism to handle the per `kid` response. 

*Any thoughts or concerns about this approach* before I open a pull request?

**Comment by adamjmcgrath** [comment]
Hi @jmaxxz - thanks for raising this

> It would seem to me that a default limit of ~30 would make more sense

This would be a breaking change, so we're not interested in doing this at the moment - however we will look into this when we next do a major release on this library

> I would like to make a change so that getSigningKeys() is cached. This would allow prefetching all currently known keys without having to know the/a kid.

This library offers the extensibility to do this if you want, by providing a [getKeysInterceptor](https://github.com/auth0/node-jwks-rsa/blob/master/index.d.ts#L34) option

Thanks for the suggestions and the offer of a PR, but we're not looking to change the behaviour of the library at this time.
