### ISSUE TITLE
strictSsl property not available jwksRsa.hapiJwt2KeyAsync

### ISSUE THREAD

**Issue by bharat-vaggu** [auth0/node-jwks-rsa#364]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/node-jwks-rsa#readme) and [Examples](https://github.com/auth0/node-jwks-rsa/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/node-jwks-rsa/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Earlier I was using jwks-rsa version 1.12.2 strictSsl property supported but now I am using jwks-rsa version 2.0.0 and strictSsl is not supported. Is there any alternate for this?

jwksRsa.hapiJwt2KeyAsync({
     strictSsl: true
})

### Reproduction

Install jwks-rsa 2.0.0

jwksRsa.hapiJwt2KeyAsync({
     strictSsl: true
})

### jwks-rsa version

2.0.0

### Node.js version

16

**Comment by adamjmcgrath** [comment]
Hi @bharat-vaggu - thanks for raising this

`true` is the default, so if that's what you need it for, you don't need to pass the `strictSsl` option.

If you want to ignore ssl errors - you can pass the `agent` option with an `https.Agent`, eg

```js
jwksRsa.hapiJwt2KeyAsync({
  agent: new https.Agent({  
    rejectUnauthorized: false
  })
});
```

**Comment by bharat-vaggu** [comment]
Thanks for the quick response.
