### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by datajohnny** [auth0/node-jwks-rsa#37]
hi is there any work currently being done to update the hapi integration to support the lastest version of hapijs

**Comment by kajlund** [comment]
I would need this too. Does not seem to be working currently with latest style of hapi-auth-jwt2

**Comment by dupski** [comment]
+1

**Comment by diegobfernandez** [comment]
It seems #38 fix it. Just need to merge it now. This is the only thing holding me back to publish my x17 upgrade.

**Comment by diegobfernandez** [comment]
Now that #38 is merged we have wait to #44

**Comment by jl-dos** [comment]
This was helpful for the complete:true and the different key validation function needed for v17.
https://github.com/auth0/node-jwks-rsa/tree/master/examples/hapi-demo

**Comment by michalczukm** [comment]
It works fine but I faced some issues due to lack of documentation, I described the example usage in SO answer: https://stackoverflow.com/a/51995573/2029818.

Maybe its worth to add a example usage for hapi v17? I can do it, but please point me in which file I should add it.

**Comment by nonniv** [comment]
Hi, when trying the example for Hapi v.17.x.x I get this error:
in ..../node_modules/jwks-rsa/lib/integrations/hapi.js:63
return cb(null, key.publicKey || key.rsaPublicKey, key);

And the function there is:
  return function secretProvider(decoded, cb) {
    // We cannot find a signing certificate if there is no header (no kid).
    if (!decoded || !decoded.header) {
      return cb(null, null, null);
    }

    // Only RS256 is supported.
    if (decoded.header.alg !== 'RS256') {
      return cb(null, null, null);
    }

    client.getSigningKey(decoded.header.kid, function (err, key) {
      if (err) {
        return onError(err, function (newError) {
          return cb(newError, null, null);
        });
      }

      // Provide the key.
      return cb(null, key.publicKey || key.rsaPublicKey, key);
    });
  };

under the comment Provide the key, cb is not in scope, try'ed to move it and that resulted in some other errors, don´t now the code to be able to figure it out.

**Comment by damieng** [comment]
This work was complete, I think if the docs need work we should track that on another issue/PR.
