### ISSUE TITLE
Consider outputting ESM

### ISSUE THREAD

**Issue by acidoxee** [auth0/node-jwks-rsa#378]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/node-jwks-rsa#readme) and [Examples](https://github.com/auth0/node-jwks-rsa/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/node-jwks-rsa/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The current package is CJS-only. The package itself isn't that heavy, but it being in CJS has the downside of also pulling all transitive dependencies as CJS, despite some of them providing ESM entrypoints (including the heaviest dependency, `jose`).

### Describe the ideal solution

It would be great if `jwks-rsa` were a dual CJS/ESM package, with "real" entrypoints for each (not just a thin wrapper of the one around the other). ESM consumers would be able to leverage proper tree-shaking of not only `jwks-rsa`, but also of its transitive dependencies that provide ESM entrypoints like `jose`, which are incredibly heavy in CJS and would be way lighter in ESM.

**Comment by adamjmcgrath** [comment]
Hi @acidoxee - thanks for raising this

We don't have any plans to convert this package to dual CJS/ESM, but I'll leave this open as an enhancement in case anyone wants to raise a PR

**Comment by acidoxee** [comment]
Hey @adamjmcgrath, I've just submitted #380 which I believe addresses a good portion of the migration towards dual CJS/ESM. There's still some work to do to fix existing (but until then, masked/missed) typing errors, fix examples and update the README and changelog to advertise for the potential breaking change.

I'll let you check the PR itself, and if you have time to review it I'd be happy to try and finish it with you or other maintainers, since it would progress quicker with your inputs and help 🙏

**Comment by acidoxee** [comment]
As I stated [in the related PR](https://github.com/auth0/node-jwks-rsa/pull/380#issuecomment-2395411465), I'll close this issue now.
