### ISSUE TITLE
types referred in dependencies section of package json

### ISSUE THREAD

**Issue by manpreet-compro** [auth0/node-jwks-rsa#384]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/node-jwks-rsa#readme) and [Examples](https://github.com/auth0/node-jwks-rsa/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/node-jwks-rsa/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Package json of the project has 2 packages only for types
```
"@types/express": "^4.17.17",
"@types/jsonwebtoken": "^9.0.2",
```
These are only providing the type definitions and ideally should be in devDependencies folder.

This create the issue of large package size. On doing production npm install `npm install --production` 
Size of `node_modules` folder is 5.33MB of which `@types` folder is of 4.08 MB

This is significant in the use case when this library is used in AWS Lambda - who is known to have higher cold start time dependeing on the package size

Package json should be updated and has only those dependenies which are required for production code

### Reproduction

Install the dependencies using `npm install --production`

### jwks-rsa version

3.1.0

### Node.js version

18.17.0

**Comment by adamjmcgrath** [comment]
Hi @manpreet-compro  - there's been some back and forth on this. In the end we decided to stick to it in dependencies - See https://github.com/auth0/node-jwks-rsa/pull/80#pullrequestreview-244880314

**Comment by manpreet-compro** [comment]
@adamjmcgrath Thanks for the reference
