### ISSUE TITLE
Capability to retrieve cacheMaxAge(from Cache-Control : max-age ) header of the Jwks End Point

### ISSUE THREAD

**Issue by saikumarr** [auth0/node-jwks-rsa#39]
Hi,

It would be cool if the library has the capability to read the max-age value from JWKS Keys http endpoint set in Cache-Control.

This java Library does the caching with the max-age directive in Cache-Control header if set in Jwks Public keys Http Endpoint
https://bitbucket.org/b_c/jose4j/wiki/JWT%20Examples#markdown-header-using-jwks

Something of this sort will be beneficent.

Thanks
Sai

**Comment by SebC99** [comment]
Hello, is this something considered or not at all?

**Comment by taeold** [comment]
Would the maintainer be interested in taking in a PR that implements this feature?

**Comment by MRamos62786** [comment]
@taeold Do you happen to have a fork of this library with this functionality implemented? 

I wonder if because this issue is closed and marked stale, the maintainers are not aware of your outstanding question...
