### ISSUE TITLE
No support for Cloudflare Workers

### ISSUE THREAD

**Issue by sgammon** [auth0/node-jwks-rsa#392]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/node-jwks-rsa#readme) and [Examples](https://github.com/auth0/node-jwks-rsa/blob/master/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/node-jwks-rsa/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

This package doesn't support environments like Cloudflare Workers. It [totally can](#243), [it just doesn't](#313).

### Reproduction

1. Try to use this library on Cloudflare Workers
2. You can't
3. See below

```
✘ [ERROR] Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor
```

### Additional context

Please? Node compat on Workers has improved substantially. Perhaps this can be fixed with better environment checking against XHR?

### jwks-rsa version

3.1.0

### Node.js version

20.x

**Comment by panva** [comment]
There is no `XMLHttpRequest` use in jwks-rsa or its runtime dependencies. Your issue is likely coming from somewhere else, perhaps an unfortunate polyfill that's part of your build pipeline, or just something else.

**Comment by zmeecer** [comment]
I faced with the similar error for Edge Runtimes (setImmetidate) and was trying to polyfill - without a significant success.
Looks like the supported runtimes can be highlighted and (ideally) broadly supported in the lib

**Comment by sgammon** [comment]
I have since realized that `jose` is the right library to use for this, which is also written by @panva. I understand why they split the libraries. Thank you for your hard work on all these libs @panva. Closing this
