### ISSUE TITLE
Support for other algorithms?

### ISSUE THREAD

**Issue by thomaux** [auth0/node-jwks-rsa#40]
I'm currently looking for a library facilitating getting the keys from a JWKS endpoint. However, in our application we're using the ES256 algorithm for signing. I'm thus a little bit bummed to notice this library, which would seem to be a perfect fit for the problem I'm trying to solve, has a hard coded check on the key type.

I'm wondering:

- as to why there's only support for the RSA algorithm
- if there are plans to support other algorithms in the future
- if you know any alternatives (after some extensive Googling, I have found none)
- whether you would be open to a PR supporting other algorithms

Many thanks,
Thomas

**Comment by whatupdave** [comment]
Or at least throw an error maybe? Took a while to figure this out.

**Comment by ShahOfMEC** [comment]
I have an application that is using ES256 as well and the lack of support for that is hurting, did you find any solution @thomaux

**Comment by thomaux** [comment]
@ShahOfMEC We have a custom implementation, but I'd rather replace that with a tried and tested one.

**Comment by wyattjoh** [comment]
Also very interested if anyone has an alternative library that we can use with https://github.com/coralproject/talk!

**Comment by danielcherubini** [comment]
@wyattjoh  I built a EC library that's a fork of this one

https://gitlab.com/danielcherubini/node-jwks-ec
