### ISSUE TITLE
koaJwtSecret type declaration is incorrect

### ISSUE THREAD

**Issue by asafigan** [auth0/node-jwks-rsa#46]
This is causing errors in my typeScript code.

**Comment by cocojoe** [comment]
Care to share some information that would help address this issue?
What is your setup? What is the actual error message you are seeing?
Thx

**Comment by asafigan** [comment]
Sorry, I was frustrated when I opened this issue so I didn't elaborate.

The types for hapiJwt2Key, hapiJwt2KeyAsync, and koaJwtSecret are all the same, which is not true. It looks like they where just copied and pasted for each other. koaJwtSecret is wrong; the others might be wrong to.

What it is now:
```
function koaJwtSecret(options: JwksRsa.Options): (name: string, scheme: string, options?: any) => void;
```

If you read the source code, the return type is completely wrong. It is more like:
```
function koaJwtSecret(options: JwksRsa.Options): (options: {alg: string, kid: string}) => Promise<string>;
```

I am not sure that the inputs and promise are all strings by reading just `src/integrations/koa.js`, but that is my best guess.

**Comment by IronPark** [comment]
```

**Comment by sjdweb** [comment]
This should match the signature of `SecretLoader` in `koa-jwt` package.

```typescript
export type SecretLoader = (header: any, payload: any) => Promise<string | string[] | Buffer | Buffer[]>;
```
