### ISSUE TITLE
Webpack/VueJS conflict

### ISSUE THREAD

**Issue by nielmistry** [auth0/node-jwks-rsa#48]
Whenever I import this module, compilation fails with these errors: 
```
ERROR  Failed to compile with 6 errors                                                                                                                                                                  10:22:10

These dependencies were not found:

* fs in ./node_modules/request/lib/har.js
* net in ./node_modules/forever-agent/index.js, ./node_modules/tough-cookie/lib/cookie.js and 1 other
* tls in ./node_modules/forever-agent/index.js, ./node_modules/tunnel-agent/index.js
```

When I `npm install --save fs net tls`, the first error persists and I can't run the code. 

This only happens with this module. I'm using VueJS 2.5.16

**Comment by nielmistry** [comment]
If anyone else has this issue, I fixed it by including this in my `build/webpack.base.conf.js` file: 

```
module.exports {
   ... 
  externals: { 
    fs: '{}',
    tls: '{}',
    net: '{}',
    console: '{}'
  }
}
```

**Comment by Rapsac11** [comment]
in my case I had to add ```    node: {
     fs: "empty",
     tls: "empty",
     net: "empty"
   }```
