### ISSUE TITLE
Caching concern

### ISSUE THREAD

**Issue by wmbutler** [auth0/node-jwks-rsa#49]
We have set the rate limit to 1 per minute and set the cache to true, however, we are still getting a high number of rate limit errors from our application. This seems like a bug in the caching function. Can anyone else comment on this?

```
cache: true,
 jwksRequestsPerMinute: 1,
jwksUri: "https://<our_auth0>.auth0.com/.well-known/jwks.json",
rateLimit: true
```

Here is the error. This typically occurs when we are returning 50+ items that each require authentication from a search result:

```
{name: "JwksError", message: "Too Many Requests"}
message
:
"Too Many Requests"
name
:
"JwksError"
```

**Comment by mymattcarroll** [comment]
@wmbutler, we was have the same issue, however, turned out to be problem with our code and not the library. 

Because our express application had to cater for multiple JWT issuers, we where creating the middleware on each request e.g. 

```js
const expressJWT = require('express-jwt')
const jwksRSA = require('jwks-rsa')

app.use(expressJWT({
  secret: function (req, jwtHeaders, jwtPayload, done) {
    switch (jwtPayload.iss) {
      case 'https://issuer-one': {
        jwksRSA.expressJwtSecret({
          cache: true,
          rateLimit: true,
          jwksUri: `https://issuer-one/.well-known/jwks.json`
        })(req, jwtHeaders, jwtPayload, done)
        break
      }
      case 'https://issuer-two': {
        jwksRSA.expressJwtSecret({
          cache: true,
          rateLimit: true,
          jwksUri: `https://issuer-two/.well-known/jwks.json`
        })(req, jwtHeaders, jwtPayload, done)
        break
      }
      default: {
        done(new Error('Unknown issuer'))
      }
    }
  }
}))
```

Fixed by moving the `expressJwtSecret()` functions outside of the request:

```js
const expressJWT = require('express-jwt')
const jwksRSA = require('jwks-rsa')

const issuerOne = jwksRSA.expressJwtSecret({
  cache: true,
  rateLimit: true,
  jwksUri: `https://issuer-one/.well-known/jwks.json`
})
const issuerTwo = jwksRSA.expressJwtSecret({
  cache: true,
  rateLimit: true,
  jwksUri: `https://issuer-two/.well-known/jwks.json`
})

app.use(expressJWT({
  secret: function (req, jwtHeaders, jwtPayload, done) {
    switch (jwtPayload.iss) {
      case 'https://issuer-one': {
        issuerOne(req, jwtHeaders, jwtPayload, done)
        break
      }
      case 'https://issuer-two': {
        issuerTwo(req, jwtHeaders, jwtPayload, done)
        break
      }
      default: {
        done(new Error('Unknown issuer'))
      }
    }
  }
}))
```

**Comment by sirzachary** [comment]
@wmbutler just wondering if you managed to solve this issue as we are currently facing a similar thing. This happens when we make around 50 concurrent request to our backend. Any ideas would be super helpful!

**Comment by devpascoe** [comment]
@mymattcarroll !!! i've been trying to track this one down on and off in a particular project going on 3 or 4 years now haha! Amazing! 
Load tested with BlazeMeter and looking good. Thanks!
