### ISSUE TITLE
How does the library work for a token that doesn't have kid in header, but only x5t?

### ISSUE THREAD

**Issue by Freundschaft** [auth0/node-jwks-rsa#5]
I have a token with a header that has only set the x5t field, but not the kid field, as far as I can see this lib is using only the kid value? how would be the correct way to proceed with a JWT that only has X5T in the header?

as far as I can see form my well known jwks file, both values are identical there.

**Comment by Freundschaft** [comment]
I believe that https://tools.ietf.org/html/rfc7515#section-6 states that all the header parameters jku, jwk, kid x5u, x5c, x5t and x5t#s256 could be used to identify the key used, am I missing something?

**Comment by larryboymi** [comment]
I agree. I have a case with only an `x5t` as well [this spec](https://tools.ietf.org/html/rfc7515#section-4.1) refers to most of these as optional. Is there a way we could specify which header parameter to use as the key when searching via `getSigningKey`?

**Comment by larryboymi** [comment]
FWIW... I added this for my case for now...

```
const getSigningKey = (kID) => // in case k5t is there while kID is not
  getSigningKeys()
  .then((keys) => keys.find(k => k.k5t === kID || k.kid === kID))

**Comment by williamdenton** [comment]
for reference here is the code block that has the problem:

https://github.com/auth0/node-jwks-rsa/blob/b0bce421ad4183198045f6a4795923c646ba9de6/src/JwksClient.js#L103-L109

**Comment by williamdenton** [comment]
@damieng, could this at least be triaged by an Auth0 maintainer?

**Comment by philmerrell** [comment]
This came up for us when trying to validate access_tokens through ADFS. For whatever reason, id_tokens have a kid, but access_tokens have x5t in the header. Not sure if this is all ADFS instances or only ours. We don't have control over the box, so this would be a great fix.

**Comment by dejan9393** [comment]
I actually opened up https://github.com/auth0/node-jwks-rsa/pull/55 a while ago to allow JWT's without a KID header to pass validation
