### ISSUE TITLE
Support for EC JWK format?

### ISSUE THREAD

**Issue by dteirney** [auth0/node-jwks-rsa#50]
We've been using this library to obtain the key matching the supplied kid from a 3rd party system that just moved to use EC format JWK rather than RS.

The library returns null for the key if the format isn't RS256 without any other logging, which took us a while to identify the problem.

Is there a recommended approach for also supporting EC keys for lookup from a JSON Web Key Set URL?

**Comment by danielcherubini** [comment]
I took care of this

https://gitlab.com/danielcherubini/node-jwks-ec
