### ISSUE TITLE
@types/express-jwt included in dependencies

### ISSUE THREAD

**Issue by cxtawayne** [auth0/node-jwks-rsa#52]
The `@types/express-jwt` package is added as a dependency, instead of devDependency. This is pulling a number of `@types` packages into our production build that shouldn't be necessary.

**Comment by chanlito** [comment]
I think when u compile typescript, those type definitions are gone.

**Comment by cxtawayne** [comment]
npm/yarn will still install them even with the --production flag unless they are placed in devDependencies.

**Comment by damieng** [comment]
Has been done in #91
