### ISSUE TITLE
hapiJwt2KeyAsync rejected with null

### ISSUE THREAD

**Issue by ozum** [auth0/node-jwks-rsa#57]
Hi,

Some non-valid access tokens in `hapiJwt2KeyAsync` causes "Error: Cannot throw non-error object"

Steps:
1. Add a random character beginning of the JWT access key.
2. Use invalid key for authentication

```
scheme: "jwt",
  options: {
    complete: true,
    key: jwksRsa.hapiJwt2KeyAsync({
      cache: false,
      rateLimit: true,
      jwksRequestsPerMinute: 5,
      jwksUri: "https://XXXX.eu.auth0.com/.well-known/jwks.json",
    }),
    verifyOptions: {
      audience: "https://api.XXXX.com",
      issuer: "https://XXXX.eu.auth0.com/",

      algorithms: ["RS256"],
    },
    validate: validate,
  },
```

`hapiJwt2KeyAsync()` rejects with null in file **jwks-rsa/lib/integrations/hapi.js**

```js
module.exports.hapiJwt2KeyAsync = function (options) {
  var secretProvider = module.exports.hapiJwt2Key(options);
  return function (decoded) {
    return new Promise(function (resolve, reject) {
      var cb = function cb(err, key) {
        !key || err ? reject(err) : resolve({ key: key });
      };
      secretProvider(decoded, cb);
    });
  };
};
```

Kind Regards,

**Comment by aschekatihin** [comment]
Related PR: #81

**Comment by PizzaBrandon** [comment]
I'm running into the same thing. If I receive a request with the wrong algorithm (not RS256), my server ends up generating a 500 rather than an `Unauthorized` response. I'm happy to see there's a PR approved and hope it is merged and published soon.

**Comment by damieng** [comment]
#81 merged.
