### ISSUE TITLE
dev dependency listed as runtime dependency

### ISSUE THREAD

**Issue by dinofx** [auth0/node-jwks-rsa#58]
The package.json contains:
"@types/express-jwt": "0.0.34",
as a runtime dependency.  This should be moved to dev dependencies, since types are not needed at runtime.

The declaration file in express-jwt adds properties like user to the Express.Request interface, which conflicts with other libraries an app might be using (like passport), which try to declare the same property on Express.Request.

**Comment by damieng** [comment]
Fixed in #91
