### ISSUE TITLE
Cannot GET /.well-known/jwks.json

### ISSUE THREAD

**Issue by agonbina** [auth0/node-jwks-rsa#6]
Seems like `request` is parsing the `jwksUri` and it ends up removing part of it so the request to fetch the keys fails. I am guessing this is because there is a dot in the uri i.e. in `/.well-known/`.
This is pretty much breaking the whole library for me. 

I'm running the simple quick start example that you get after you have created an API in auth0, on node v6.9.5

Any ideas what might be happening and how it could be fixed? Thanks

**Comment by bman654** [comment]
I just had the same problem.  Did you find a solution?  And how did you trace the issue to `request`?  How can I see the actual request the nodejs app makes?

**Comment by bman654** [comment]
Never mind, it turns out the problem I was having was that I didn't have my `HTTP_PROXY` and `HTTPS_PROXY` environment variables set.  Once I set them, this library worked just fine.

**Comment by agonbina** [comment]
@bman654 what values did you set them to? I'd like to try the same and see if that fixes my issue.

**Comment by bman654** [comment]
@agonbina I'm behind a corporate firewall that requires we use a proxy.  I set my variables to use that proxy.  You can try looking in your web browser internet settings to see if you are using a proxy.

In my case, I set them similar to this:

```
HTTPS_PROXY=http://blah.blah.blah.com:8080/
HTTP_PROXY=http://blah.blah.blah.com:8080/
```

**Comment by agonbina** [comment]
Hey @bman654, a proxy was the issue for me too, thanks for figuring it out. Closing this.
