### ISSUE TITLE
Dependency Request's sub dependency har-validator is causing install issues

### ISSUE THREAD

**Issue by Glathrop** [auth0/node-jwks-rsa#72]
The maintainer of har-validator unpublished v5.1.2. 

https://github.com/ahmadnassri/node-har-validator/issues/112

As it is widely used, this is causing installation issues across many packages. 

While NPM users have figured workarounds Yarn users are not able to implement these same workarounds due to differences around unpublishing a package. 

https://github.com/yarnpkg/yarn/issues/6694

I'm not super familiar on the ins and outs of sub-dependencies, but it seems like this could be avoided by requiring the most recent 2.88 version of Request. 

Thoughts?

**Comment by damieng** [comment]
Fixed in #91
