### ISSUE TITLE
snyk vulnerabilities

### ISSUE THREAD

**Issue by shavo007** [auth0/node-jwks-rsa#86]
My latest report highlighted two vulnerabilities

```
Regular Expression Denial of Service (ReDoS)
Vulnerable module: lodash
Introduced through: jwks-rsa@1.4.0
Detailed paths and remediation
Introduced through: my-project@1.0.0 › jwks-rsa@1.4.0 › lru-memoizer@1.12.0 › lodash@4.17.10
```

```
Prototype Pollution
Vulnerable module: lodash
Introduced through: jwks-rsa@1.4.0
Detailed paths and remediation
Introduced through: my-project@1.0.0 › jwks-rsa@1.4.0 › lru-memoizer@1.12.0 › lodash@4.17.10
```

Thanks,
Shane.

**Comment by sobil** [comment]
https://github.com/auth0/node-jwks-rsa/pull/106

Fix looks to be merged, thanks @damieng. Whats the eta process for deployment to npm for this one?

**Comment by damieng** [comment]
Not sure, this library need a lot more housekeeping/work on issues/PR reviews I think before we get another release out.
