### ISSUE TITLE
[NPM] version 1.5.1 is broken

### ISSUE THREAD

**Issue by enzocanoo** [auth0/node-jwks-rsa#97]
Hi, I recently tried to use the latest version `1.5.1` in a TypeScript project and it seems like it's broken. In typescript, it doesn't resolve dependencies like `express-jwt`.

Also, if I try to download the package using `npm pack jwks-rsa` I got the following message:
```
npm notice === Tarball Details ===
npm notice name:          jwks-rsa
npm notice version:       1.5.1
npm notice filename:      jwks-rsa-1.5.1.tgz
npm notice package size:  2.8 MB
npm notice unpacked size: 10.6 MB
npm notice shasum:        05b7f1ba4e9829162e2aa3ab6a79d539416de200
npm notice integrity:     sha512-FcH0mrrfS/5CD[...]Pme4fb/ZoHKqQ==
npm notice total files:   2014
npm notice
jwks-rsa-1.5.1.tgz
```

**Comment by ottokruse** [comment]
I have the same issue

**Comment by oros** [comment]
Looks related: https://github.com/auth0/node-jwks-rsa/commit/98c1c6c6109e46e3b5dae9a83098a2b0a9ce1ada

**Comment by Brunomachadob** [comment]
Yep, seems to be related to that commit.
We are having the same problem here.

**Comment by ottokruse** [comment]
It of course makes sense that express-jwt is not a dependency for people that want to use node-jwks-rsa without express (me). But then the typings shouldn't depend on it :)
